#!/usr/bin/env node
/**
 * `npm run gen:banned` — copies the backend's banned-substance list and shared
 * matcher into the app (spec D1: one copy). The backend files are the source
 * of truth; the generated files must never be edited by hand.
 * src/features/__tests__/bannedSubstances.generated.test.ts fails when a
 * generated file is stale.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SRC_DIR = path.resolve(__dirname, '../../backend/src/banned-substances');
const OUT_DIR = path.resolve(__dirname, '../src/features');

const FILES = [
  { src: 'banned-substances.data.ts', out: 'bannedSubstances.generated.ts' },
  {
    src: 'banned-substance-matcher.core.ts',
    out: 'bannedSubstanceMatcher.generated.ts',
    rewrite: (s) => s.replace("'./banned-substances.data'", "'./bannedSubstances.generated'"),
  },
];

/** Line endings are normalised so a Windows checkout hashes the same as CI. */
const lf = (s) => s.replace(/\r\n/g, '\n');

function render(file) {
  const source = lf(fs.readFileSync(path.join(SRC_DIR, file.src), 'utf8'));
  const hash = crypto.createHash('sha256').update(source).digest('hex');
  const body = file.rewrite ? file.rewrite(source) : source;
  return (
    `// GENERATED by \`npm run gen:banned\` from backend/src/banned-substances/${file.src}.\n` +
    `// Do not edit. source-sha256: ${hash}\n\n` +
    body
  );
}

if (require.main === module) {
  for (const file of FILES) {
    fs.writeFileSync(path.join(OUT_DIR, file.out), render(file));
    console.log(`wrote src/features/${file.out}`);
  }
}

module.exports = { FILES, OUT_DIR, render, lf };
