/**
 * The two renderers, against one fixture. Both read the same ReportData, so a
 * disagreement between the CSV and the XLSX shows up here rather than in a
 * document already sent to a buyer.
 */

import * as XLSX from 'xlsx';

import { toReportCsv } from '../csv';
import { toReportXlsxBase64, safeSheetName, columnWidths } from '../xlsx';
import type { ReportData } from '../types';

const fixture: ReportData = {
    meta: {
        documentTitle: 'Cycle report',
        farmName: 'Green Acres',
        pondName: 'Pond 3',
        cycleLabel: 'Cycle 7 (C-7)',
        periodLabel: '1 Jun 2026 – 5 Sep 2026',
        generatedAt: '5 Sep 2026 11:04',
        attribution: 'Generated by Neerani',
    },
    stats: [{ label: 'FCR', value: '1.42', hint: 'over 92 days' }],
    tables: [
        {
            key: 'feed',
            title: 'Feed History',
            columns: ['Date', 'Feed type', 'Quantity (kg)'],
            numericColumns: [2],
            rows: [
                ['24 Aug 2026', 'Starter', '12.5'],
                // The three characters that break a naive join(','):
                ['25 Aug 2026', 'Grower, 2mm "premium"\nnew batch', '13'],
            ],
            total: ['', 'Total', '25.5'],
        },
    ],
    disclaimer: 'A record of what was entered, not a guarantee.',
};

describe('toReportCsv', () => {
    it('escapes a cell with a comma, a quote and a newline', () => {
        const csv = toReportCsv(fixture);
        expect(csv).toContain('"Grower, 2mm ""premium""\nnew batch"');
    });

    it('separates tables with a blank line and a title row', () => {
        const csv = toReportCsv(fixture);
        expect(csv).toContain('\n\nFeed History\nDate,Feed type,Quantity (kg)\n');
        expect(csv).toContain('Generated by Neerani');
    });

    it('emits the total row last in the table block', () => {
        const csv = toReportCsv(fixture);
        expect(csv).toContain(',Total,25.5');
    });
});

describe('safeSheetName', () => {
    it('strips the characters Excel refuses and truncates to 31', () => {
        const name = safeSheetName('Water/Quality: [2026] *history* of a very long pond name', new Set());
        expect(name).not.toMatch(/[[\]:*?/\\]/);
        expect(name.length).toBeLessThanOrEqual(31);
    });

    it('de-duplicates names that collide after truncation', () => {
        const taken = new Set<string>();
        const a = safeSheetName('Expenses', taken);
        const b = safeSheetName('Expenses', taken);
        expect(a).toBe('Expenses');
        expect(b).toBe('Expenses (2)');
    });
});

describe('toReportXlsxBase64', () => {
    const book = () => XLSX.read(toReportXlsxBase64(fixture), { type: 'base64' });

    it('writes a summary sheet first, then one sheet per table', () => {
        expect(book().SheetNames).toEqual(['Summary', 'Feed History']);
    });

    it('round-trips a table to the expected cells', () => {
        const sheet = book().Sheets['Feed History'];
        expect(sheet.A1.v).toBe('Feed History');
        expect(sheet.A2.v).toBe('Date');
        expect(sheet.B3.v).toBe('Starter');
        expect(sheet.C3.v).toBe('12.5');
        expect(sheet.B4.v).toBe('Grower, 2mm "premium"\nnew batch');
        expect(sheet.C5.v).toBe('25.5');
    });

    it('puts the meta block and the stats on the summary sheet', () => {
        const sheet = book().Sheets.Summary;
        const text = XLSX.utils.sheet_to_csv(sheet);
        expect(text).toContain('Cycle report');
        expect(text).toContain('Green Acres');
        expect(text).toContain('1 Jun 2026 – 5 Sep 2026');
        expect(text).toContain('FCR');
    });

    // `!cols` does not survive a read round-trip, so widths are checked at the
    // source: never the 8-character default, never a mile wide.
    it('sizes columns to their content', () => {
        expect(columnWidths([['Date', 'x'], ['24 Aug 2026', 'y'.repeat(200)]]))
            .toEqual([{ wch: 13 }, { wch: 50 }]);
    });
});
