/**
 * The contract every export layer builds against.
 *
 * Three layers, deliberately separated so each is testable without the others:
 *   collect  — API/query data  ->  ReportData   (features/export/collect.ts)
 *   render   — ReportData      ->  HTML | XLSX | CSV
 *   deliver  — bytes           ->  a file the farmer can share
 *
 * ReportData is the seam. It is plain, already-formatted data: no promises, no
 * query clients, no React. That is what lets the PDF template be unit-tested
 * against a fixture and the XLSX writer be checked cell by cell.
 *
 * NOTHING here is analytics. Exports contain the farmer's own farm records,
 * money and harvest figures — that is the entire point of an export, and it is
 * the opposite of what may be sent to PostHog. Do not route export payloads
 * through `capture()`; the allowlist would drop them anyway, but the intent
 * matters. Only the FACT that an export happened is reported.
 */

export type ExportFormat = 'pdf' | 'xlsx' | 'csv';

export type ExportDataset =
    | 'cycle'      // one crop, stocking through harvest — the flagship report
    | 'pondLogs'   // raw records over a date range
    | 'money'      // expenses and income
    | 'inventory'
    | 'attendance'
    | 'tasks'
    | 'inputRecord'; // D4: one cycle's inputs + health, for a processor. No money.

/**
 * Which blocks the farmer chose to include. A farmer sending a report to a
 * BUYER very often does not want their cost breakdown in it — that is a real
 * privacy need, not a display preference, so every section is opt-out and the
 * renderer must honour an absent section by omitting it entirely rather than
 * printing an empty heading.
 */
export interface ExportSections {
    summary: boolean;
    waterQuality: boolean;
    feed: boolean;
    sampling: boolean;
    mortality: boolean;
    treatments: boolean;
    /** Disease records (D6): disease, severity, confirmation, outcome. */
    disease: boolean;
    costs: boolean;
    harvest: boolean;
}

export const ALL_SECTIONS: ExportSections = {
    summary: true,
    waterQuality: true,
    feed: true,
    sampling: true,
    mortality: true,
    treatments: true,
    disease: true,
    costs: true,
    harvest: true,
};

export interface ExportConfig {
    dataset: ExportDataset;
    format: ExportFormat;
    /** Inclusive, IST-local `YYYY-MM-DD`, matching the money-screen ranges. */
    startDate?: string;
    endDate?: string;
    /** Attendance: optional — absent means every farm the caller can see. */
    farmId?: string;
    /** Attendance: one person's rows only. */
    userId?: string;
    pondId?: string;
    cropId?: string;
    sections: ExportSections;
    /**
     * Locale for the DOCUMENT, which need not be the app's. A farmer may read
     * Tamil but need an English report for a buyer or a lender.
     */
    language: string;
    includeArchived?: boolean;
}

/** One rendered table. Cells are pre-formatted strings — no locale logic downstream. */
export interface ReportTable {
    /** Section key, so a renderer can skip a table the farmer excluded. */
    key: keyof ExportSections;
    title: string;
    columns: string[];
    rows: string[][];
    /** Right-align these column indices (numbers, money). */
    numericColumns?: number[];
    /** Optional footer row, e.g. totals. Rendered distinctly. */
    total?: string[];
}

/** A headline figure on the summary card row. */
export interface ReportStat {
    label: string;
    value: string;
    /** Optional qualifier, e.g. "over 92 days". */
    hint?: string;
}

export interface ReportMeta {
    /** e.g. "Cycle report" — already translated. */
    documentTitle: string;
    farmName?: string;
    pondName?: string;
    cycleLabel?: string;
    /** Human date range, already formatted, e.g. "1 Jun – 5 Sep 2026". */
    periodLabel?: string;
    /** When the document was produced, already formatted. */
    generatedAt: string;
    /** Localised "Generated by Neerani" style attribution. */
    attribution: string;
}

/**
 * Everything a renderer needs, and nothing it does not. Fully formatted and
 * fully translated: a renderer never calls `t()`, never touches a Date, and
 * never formats a number — so the same fixture proves the PDF, the XLSX and
 * the CSV all agree.
 */
export interface ReportData {
    meta: ReportMeta;
    stats: ReportStat[];
    tables: ReportTable[];
    /**
     * Shown in small print at the foot of the document. Carries the same
     * decision-support disclaimer as the Terms: these figures are a record of
     * what was entered, not a guarantee of anything.
     */
    disclaimer: string;
}

/** What a completed export produced, for sharing and for the success message. */
export interface ExportResult {
    uri: string;
    filename: string;
    mimeType: string;
    format: ExportFormat;
}

export const MIME: Record<ExportFormat, string> = {
    pdf: 'application/pdf',
    xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    csv: 'text/csv',
};
