// GENERATED by `npm run gen:banned` from backend/src/banned-substances/banned-substances.data.ts.
// Do not edit. source-sha256: a769e92f55221ea8d9af8ffc5f3ce6440ea931319716ffb3c36997d95fb59097

// DRAFT — NOT REVIEWED. Do not ship until a named reviewer fills REVIEWED_BY.
//
// Banned / restricted aquaculture-substance list, v2 (spec D1:
// docs/superpowers/specs/2026-09-19-disease-health-compliance-design.md).
//
// Served by GET /banned-substances and copied VERBATIM into the app by
// `npm run gen:banned` (frontend/scripts/gen-banned.js). This file must stay
// import-free so the copy compiles on both sides. Edit it here only.
//
// Rules for editing:
// - Every entry cites the primary instrument it comes from (`sources`), with a
//   URL that was actually opened. An entry with no verified primary source keeps
//   `sources: []` and a note starting 'UNSOURCED'. Never invent a citation.
// - `aliases` are Latin-script spellings (incl. known misspellings). They are
//   also what OLD app builds match on, so this field must stay a string[].
// - `localAliases` are native-script names. Every locale block is a machine
//   transliteration — needs native-speaker check (hi, te, ta, bn, or).
// - Lab-report metabolite codes (AOZ, AMOZ, SEM, AHD) live in `labCodes`, never
//   in `aliases`: as free text they match ordinary words ("sem" in a sentence).
// - Bump BANNED_LIST_VERSION on every change. REVIEWED_BY is a person, not an
//   agent, and is filled only after checking every entry against the sources.
//
// Decision-support only. Not legal advice. Never suggests an alternative.

export type SubstanceCategory = 'banned' | 'restricted';
export type SubstanceKind =
  | 'antibiotic'
  | 'antiviral'
  | 'antiprotozoal'
  | 'hormone'
  | 'dye'
  | 'other';
export type LocalAliasLocale = 'hi' | 'te' | 'ta' | 'bn' | 'or';

export interface BannedSource {
  authority: string;
  instrument: string;
  /** Item / section inside the instrument, e.g. 'Annex (1)(g)'. */
  ref?: string;
  url: string;
}

export interface BannedSubstance {
  /** Stable id (used by D2 ingredients). Never rename. */
  key: string;
  /** Canonical display name. Also what the server stores in `matches`. */
  name: string;
  category: SubstanceCategory;
  kind: SubstanceKind;
  sources: BannedSource[];
  /** Latin-script spellings. Old clients match on this field. */
  aliases: string[];
  /** Native-script names per locale. */
  localAliases?: Partial<Record<LocalAliasLocale, string[]>>;
  /** Lab-report codes. Never matched against free text. */
  labCodes?: string[];
  /** Brand names, added only when verified. */
  brands?: string[];
  note?: string;
}

export const BANNED_LIST_VERSION = '2026-09-19';
/** ISO date the named reviewer checked the list. null = not reviewed. */
export const BANNED_LIST_REVIEWED_ON: string | null = null;
/** Named human reviewer. Empty = DRAFT; must not ship. */
export const BANNED_LIST_REVIEWED_BY: string = '';

// ── Primary instruments (each URL was opened when this list was drafted) ─────

const CAA_RULES_TABLE5: BannedSource = {
  authority: 'CAA',
  instrument:
    'Coastal Aquaculture Authority Rules, 2005 (G.S.R. 740(E), 22 Dec 2005), Guidelines §11.7 Table 5: antibiotics and pharmacologically active substances banned in shrimp aquaculture',
  url: 'https://caa.gov.in/uploaded/doc/compendium_act.pdf',
};
const CAA_WEB_LIST: BannedSource = {
  authority: 'CAA',
  instrument:
    'CAA: List of antibiotics and other pharmacologically active substances banned for using in shrimp aquaculture (undated)',
  url: 'https://caa.gov.in/uploaded/doc/Pharmacologically.pdf',
};
const CAA = [CAA_RULES_TABLE5, CAA_WEB_LIST];
const CAA_MRL: BannedSource = {
  authority: 'CAA',
  instrument:
    'Coastal Aquaculture Authority Rules, 2005, Guidelines Appendix: Maximum Permissible Residual Levels for Fish and Fishery Products',
  url: 'https://caa.gov.in/uploaded/doc/compendium_act.pdf',
};
const MOHFW_SO_1158: BannedSource = {
  authority: 'MoHFW',
  instrument:
    'S.O. 1158(E), 12 Mar 2025 (Drugs and Cosmetics Act 1940, s.26A): chloramphenicol and nitrofurans prohibited for use in any food-producing animal rearing system',
  url: 'https://drugscontrol.py.gov.in/sites/default/files/2025-03/S.O.-1158E-dt-12-03-2025-Section-26A-Chloramphenicol-and-Nitrofurans-Banned-in-food-producing-animals.pdf',
};
const eu = (ref: string): BannedSource => ({
  authority: 'EU',
  instrument:
    'Commission Implementing Regulation (EU) 2022/1255 of 19 July 2022: antimicrobials reserved for treatment of certain infections in humans',
  ref: `Annex ${ref}`,
  url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R1255',
});

const DOC_2025 =
  'Reported (May 2025) as also prohibited in Indian aquaculture by the Dept of Commerce order under the Export (Quality Control and Inspection) Act, 1963; primary order text not located, reviewer to add its S.O. number.';
const UNSOURCED = 'UNSOURCED — reviewer must verify.';

const EU_ANTIVIRALS: Array<[key: string, name: string, ref: string, extra: string[]]> = [
  ['amantadine', 'Amantadine', '(2)(a)', []],
  ['baloxavir_marboxil', 'Baloxavir marboxil', '(2)(b)', ['baloxavir']],
  ['celgosivir', 'Celgosivir', '(2)(c)', []],
  ['favipiravir', 'Favipiravir', '(2)(d)', []],
  ['galidesivir', 'Galidesivir', '(2)(e)', []],
  ['lactimidomycin', 'Lactimidomycin', '(2)(f)', []],
  ['laninamivir', 'Laninamivir', '(2)(g)', []],
  ['methisazone', 'Methisazone', '(2)(h)', ['metisazone']],
  ['molnupiravir', 'Molnupiravir', '(2)(i)', []],
  ['oseltamivir', 'Oseltamivir', '(2)(k)', []],
  ['peramivir', 'Peramivir', '(2)(l)', []],
  ['ribavirin', 'Ribavirin', '(2)(m)', []],
  ['rimantadine', 'Rimantadine', '(2)(n)', []],
  ['tizoxanide', 'Tizoxanide', '(2)(o)', []],
  ['triazavirin', 'Triazavirin', '(2)(p)', []],
  ['umifenovir', 'Umifenovir', '(2)(q)', ['arbidol']],
  ['zanamivir', 'Zanamivir', '(2)(r)', []],
];

export const BANNED_SUBSTANCES: BannedSubstance[] = [
  // ── CAA Table 5 (banned) ───────────────────────────────────────────────────
  {
    key: 'chloramphenicol',
    name: 'Chloramphenicol',
    category: 'banned',
    kind: 'antibiotic',
    sources: [...CAA, MOHFW_SO_1158],
    aliases: ['chloramphenicol', 'chloramphenicole', 'chloramphenical', 'chloromycetin'],
    localAliases: {
      hi: ['क्लोरैम्फेनिकॉल', 'क्लोरैम्फेनिकोल'],
      te: ['క్లోరాంఫెనికాల్'],
      ta: ['குளோரம்பெனிகால்'],
      bn: ['ক্লোরামফেনিকল'],
      or: ['କ୍ଲୋରାମଫେନିକଲ'],
    },
  },
  {
    key: 'nitrofurans',
    name: 'Nitrofurans',
    category: 'banned',
    kind: 'antibiotic',
    sources: [...CAA, MOHFW_SO_1158],
    aliases: [
      'nitrofuran',
      'nitrofurans',
      'furaltadone',
      'furazolidone',
      'furazolidon',
      'furylfuramide',
      'nifuratel',
      'nifuroxime',
      'nifurprazine',
      'nitrofurantoin',
      'nitrofurazone',
      'nitrofurazon',
    ],
    localAliases: {
      hi: ['नाइट्रोफ्यूरान', 'फ्यूराज़ोलिडोन', 'फुराजोलिडोन'],
      te: ['నైట్రోఫ్యూరాన్', 'ఫ్యూరజోలిడోన్'],
      ta: ['நைட்ரோஃபுரான்', 'ஃபுராசோலிடோன்'],
      bn: ['নাইট্রোফুরান', 'ফুরাজোলিডোন'],
      or: ['ନାଇଟ୍ରୋଫୁରାନ', 'ଫୁରାଜୋଲିଡୋନ'],
    },
    labCodes: ['AOZ', 'AMOZ', 'SEM', 'AHD'],
  },
  {
    key: 'neomycin',
    name: 'Neomycin',
    category: 'banned',
    kind: 'antibiotic',
    sources: CAA,
    aliases: ['neomycin', 'neomycine', 'neomicin'],
    localAliases: {
      hi: ['नियोमाइसिन'],
      te: ['నియోమైసిన్'],
      ta: ['நியோமைசின்'],
      bn: ['নিওমাইসিন'],
      or: ['ନିଓମାଇସିନ'],
    },
  },
  {
    key: 'nalidixic_acid',
    name: 'Nalidixic acid',
    category: 'banned',
    kind: 'antibiotic',
    sources: CAA,
    aliases: ['nalidixic', 'nalidixic acid'],
    localAliases: {
      hi: ['नेलिडिक्सिक'],
      te: ['నాలిడిక్సిక్'],
      ta: ['நாலிடிக்சிக்'],
      bn: ['ন্যালিডিক্সিক'],
      or: ['ନାଲିଡିକ୍ସିକ'],
    },
  },
  {
    key: 'sulfamethoxazole',
    name: 'Sulfamethoxazole',
    category: 'banned',
    kind: 'antibiotic',
    sources: CAA,
    // 'sulph…' spellings are covered by the matcher's Latin ph→f rule.
    aliases: ['sulfamethoxazole', 'sulfamethoxazol', 'cotrimoxazole', 'co-trimoxazole'],
    localAliases: {
      hi: ['सल्फामेथोक्साजोल'],
      te: ['సల్ఫామెథోక్సజోల్'],
      ta: ['சல்பாமெத்தாக்சசோல்'],
      bn: ['সালফামেথক্সাজল'],
      or: ['ସଲଫାମେଥୋକ୍ସାଜୋଲ'],
    },
    note: 'Co-trimoxazole = sulfamethoxazole + trimethoprim.',
  },
  {
    key: 'sulfonamides',
    name: 'Sulfonamides',
    category: 'banned',
    kind: 'antibiotic',
    sources: CAA,
    aliases: [
      'sulfonamide',
      'sulfonamides',
      'sulfa drug',
      'sulfa drugs',
      'sulfadiazine',
      'sulfadimidine',
      'sulfamethazine',
      'sulfaquinoxaline',
      'sulfathiazole',
      'sulfaguanidine',
      'sulfamerazine',
      'sulfachloropyridazine',
      'sulfamonomethoxine',
    ],
    localAliases: {
      hi: ['सल्फोनामाइड'],
      te: ['సల్ఫోనమైడ్'],
      ta: ['சல்போனமைடு'],
      bn: ['সালফোনামাইড'],
      or: ['ସଲଫୋନାମାଇଡ'],
    },
    note: 'CAA exempts sulfadimethoxine, sulfabromomethazine and sulfaethoxypyridazine; they are deliberately not aliases.',
  },
  {
    key: 'aristolochia',
    name: 'Aristolochia',
    category: 'banned',
    kind: 'other',
    sources: CAA,
    aliases: ['aristolochia', 'aristolochic'],
    note: 'Aristolochia spp. and preparations thereof.',
  },
  {
    key: 'chloroform',
    name: 'Chloroform',
    category: 'banned',
    kind: 'other',
    sources: CAA,
    aliases: ['chloroform'],
    localAliases: {
      hi: ['क्लोरोफॉर्म'],
      te: ['క్లోరోఫామ్'],
      ta: ['குளோரோஃபார்ம்'],
      bn: ['ক্লোরোফর্ম'],
      or: ['କ୍ଲୋରୋଫର୍ମ'],
    },
  },
  {
    key: 'chlorpromazine',
    name: 'Chlorpromazine',
    category: 'banned',
    kind: 'other',
    sources: CAA,
    aliases: ['chlorpromazine'],
  },
  {
    key: 'colchicine',
    name: 'Colchicine',
    category: 'banned',
    kind: 'other',
    sources: CAA,
    aliases: ['colchicine'],
  },
  {
    key: 'dapsone',
    name: 'Dapsone',
    category: 'banned',
    kind: 'antibiotic',
    sources: CAA,
    aliases: ['dapsone'],
    localAliases: {
      hi: ['डैप्सोन'],
      te: ['డాప్సోన్'],
      ta: ['டாப்சோன்'],
      bn: ['ড্যাপসোন'],
      or: ['ଡାପସୋନ'],
    },
  },
  {
    key: 'nitroimidazoles',
    name: 'Nitroimidazoles',
    category: 'banned',
    kind: 'antiprotozoal',
    sources: CAA,
    aliases: [
      'nitroimidazole',
      'nitroimidazoles',
      'dimetridazole',
      'metronidazole',
      'metronidazol',
      'ronidazole',
      'ipronidazole',
      'tinidazole',
      'ornidazole',
      'secnidazole',
    ],
    localAliases: {
      hi: ['मेट्रोनिडाजोल'],
      te: ['మెట్రోనిడజోల్'],
      ta: ['மெட்ரோனிடசோல்'],
      bn: ['মেট্রোনিডাজল'],
      or: ['ମେଟ୍ରୋନିଡାଜୋଲ'],
    },
    note: 'CAA lists dimetridazole, metronidazole, ronidazole, ipronidazole and "other nitroimidazoles"; tinidazole, ornidazole and secnidazole are added as members of that class.',
  },
  {
    key: 'clenbuterol',
    name: 'Clenbuterol',
    category: 'banned',
    kind: 'other',
    sources: CAA,
    aliases: ['clenbuterol'],
  },
  {
    key: 'diethylstilbestrol',
    name: 'Diethylstilbestrol (DES)',
    category: 'banned',
    kind: 'hormone',
    sources: CAA,
    // 'DES' alone is too short to match safely in free text.
    aliases: ['diethylstilbestrol', 'diethylstilboestrol', 'stilbestrol', 'stilboestrol'],
  },
  {
    key: 'fluoroquinolones',
    name: 'Fluoroquinolones',
    category: 'banned',
    kind: 'antibiotic',
    sources: CAA,
    aliases: [
      'fluoroquinolone',
      'fluoroquinolones',
      'fluroquinolone',
      'fluroquinolones',
      'ciprofloxacin',
      'ciprofloxacine',
      'enrofloxacin',
      'enrofloxacine',
      'norfloxacin',
      'ofloxacin',
      'levofloxacin',
      'pefloxacin',
      'sarafloxacin',
      'danofloxacin',
      'difloxacin',
      'marbofloxacin',
      'flumequine',
    ],
    localAliases: {
      hi: ['सिप्रोफ्लोक्सासिन', 'एनरोफ्लोक्सासिन', 'नॉरफ्लोक्सासिन', 'ओफ़्लॉक्सासिन'],
      te: ['సిప్రోఫ్లాక్సాసిన్', 'ఎన్రోఫ్లాక్సాసిన్', 'నార్ఫ్లాక్సాసిన్', 'ఆఫ్లాక్సాసిన్'],
      ta: ['சிப்ரோஃப்ளாக்சசின்', 'என்ரோஃப்ளாக்சசின்', 'நார்ஃப்ளாக்சசின்', 'ஆஃப்லாக்சசின்'],
      bn: ['সিপ্রোফ্লক্সাসিন', 'এনরোফ্লক্সাসিন', 'নরফ্লক্সাসিন', 'অফলক্সাসিন'],
      or: ['ସିପ୍ରୋଫ୍ଲକ୍ସାସିନ', 'ଏନ୍ରୋଫ୍ଲକ୍ସାସିନ', 'ନରଫ୍ଲକ୍ସାସିନ', 'ଅଫ୍ଲକ୍ସାସିନ'],
    },
    note: 'CAA spells the class "Fluroquinolones"; individual drugs are added as members of the class.',
  },
  {
    key: 'glycopeptides',
    name: 'Glycopeptides',
    category: 'banned',
    kind: 'antibiotic',
    sources: [...CAA, eu('(1)(k)')],
    aliases: [
      'glycopeptide',
      'glycopeptides',
      'vancomycin',
      'avoparcin',
      'teicoplanin',
      'dalbavancin',
      'oritavancin',
      'telavancin',
    ],
  },

  // ── CAA Appendix: residue-limited (restricted) ─────────────────────────────
  {
    key: 'oxytetracycline',
    name: 'Oxytetracycline',
    category: 'restricted',
    kind: 'antibiotic',
    sources: [CAA_MRL],
    aliases: ['oxytetracycline', 'oxytetracyclin', 'terramycin'],
    localAliases: {
      hi: ['ऑक्सीटेट्रासाइक्लिन'],
      te: ['ఆక్సిటెట్రాసైక్లిన్'],
      ta: ['ஆக்ஸிடெட்ராசைக்ளின்'],
      bn: ['অক্সিটেট্রাসাইক্লিন'],
      or: ['ଅକ୍ସିଟେଟ୍ରାସାଇକ୍ଲିନ'],
    },
    note: 'Max residue 0.1 ppm (CAA Appendix). Confirm the withdrawal period with your processor.',
  },
  {
    key: 'tetracycline',
    name: 'Tetracycline',
    category: 'restricted',
    kind: 'antibiotic',
    sources: [CAA_MRL],
    aliases: ['tetracycline', 'tetracyclin'],
    localAliases: {
      hi: ['टेट्रासाइक्लिन'],
      te: ['టెట్రాసైక్లిన్'],
      ta: ['டெட்ராசைக்ளின்'],
      bn: ['টেট্রাসাইক্লিন'],
      or: ['ଟେଟ୍ରାସାଇକ୍ଲିନ'],
    },
    note: 'Max residue 0.1 ppm (CAA Appendix).',
  },
  {
    key: 'trimethoprim',
    name: 'Trimethoprim',
    category: 'restricted',
    kind: 'antibiotic',
    sources: [CAA_MRL],
    aliases: ['trimethoprim'],
    localAliases: {
      hi: ['ट्राइमेथोप्रिम'],
      te: ['ట్రైమెథోప్రిమ్'],
      ta: ['டிரைமெத்தோபிரிம்'],
      bn: ['ট্রাইমেথোপ্রিম'],
      or: ['ଟ୍ରାଇମେଥୋପ୍ରିମ'],
    },
    note: 'Max residue 0.05 ppm (CAA Appendix).',
  },
  {
    key: 'oxolinic_acid',
    name: 'Oxolinic acid',
    category: 'restricted',
    kind: 'antibiotic',
    sources: [CAA_MRL],
    aliases: ['oxolinic', 'oxolinic acid'],
    note: 'Max residue 0.3 ppm (CAA Appendix).',
  },

  // ── EU 2022/1255 Annex (1): antibiotics reserved for humans ────────────────
  {
    key: 'carboxypenicillins',
    name: 'Carboxypenicillins',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(a)')],
    aliases: ['carboxypenicillin', 'carboxypenicillins', 'carbenicillin', 'ticarcillin', 'carindacillin'],
    note: DOC_2025,
  },
  {
    key: 'ureidopenicillins',
    name: 'Ureidopenicillins',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(b)')],
    aliases: ['ureidopenicillin', 'ureidopenicillins', 'piperacillin', 'azlocillin', 'mezlocillin'],
    note: DOC_2025,
  },
  {
    key: 'ceftobiprole',
    name: 'Ceftobiprole',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(c)')],
    aliases: ['ceftobiprole'],
    note: DOC_2025,
  },
  {
    key: 'ceftaroline',
    name: 'Ceftaroline',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(d)')],
    aliases: ['ceftaroline'],
    note: DOC_2025,
  },
  {
    key: 'cephalosporin_bli',
    name: 'Cephalosporin + beta-lactamase inhibitor combinations',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(e)')],
    aliases: [
      'avibactam',
      'ceftolozane',
      'ceftazidime avibactam',
      'ceftolozane tazobactam',
      'cefoperazone sulbactam',
      'ceftriaxone sulbactam',
      'ceftriaxone tazobactam',
      'cefepime tazobactam',
      'cefepime enmetazobactam',
    ],
    note: DOC_2025,
  },
  {
    key: 'siderophore_cephalosporins',
    name: 'Siderophore cephalosporins',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(f)')],
    aliases: ['cefiderocol'],
    note: DOC_2025,
  },
  {
    key: 'carbapenems',
    name: 'Carbapenems',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(g)')],
    aliases: [
      'carbapenem',
      'carbapenems',
      'meropenem',
      'imipenem',
      'ertapenem',
      'doripenem',
      'biapenem',
      'tebipenem',
    ],
    note: DOC_2025,
  },
  {
    key: 'penems',
    name: 'Penems',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(h)')],
    aliases: ['penem', 'penems', 'faropenem', 'sulopenem'],
    note: DOC_2025,
  },
  {
    key: 'monobactams',
    name: 'Monobactams',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(i)')],
    aliases: ['monobactam', 'monobactams', 'aztreonam'],
    note: DOC_2025,
  },
  {
    key: 'phosphonic_acid_derivatives',
    name: 'Phosphonic acid derivatives (fosfomycin)',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(j)')],
    aliases: ['fosfomycin', 'phosphomycin'],
    note: 'EU 2022/1255 lists this group. Press reports of the Dept of Commerce May 2025 order disagree on whether it is included; reviewer must check the primary order.',
  },
  {
    key: 'lipopeptides',
    name: 'Lipopeptides',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(l)')],
    aliases: ['lipopeptide', 'lipopeptides', 'daptomycin'],
    note: DOC_2025,
  },
  {
    key: 'oxazolidinones',
    name: 'Oxazolidinones',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(m)')],
    aliases: ['oxazolidinone', 'oxazolidinones', 'linezolid', 'tedizolid'],
    note: DOC_2025,
  },
  {
    key: 'fidaxomicin',
    name: 'Fidaxomicin',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(n)')],
    aliases: ['fidaxomicin'],
    note: DOC_2025,
  },
  {
    key: 'plazomicin',
    name: 'Plazomicin',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(o)')],
    aliases: ['plazomicin'],
    note: DOC_2025,
  },
  {
    key: 'glycylcyclines',
    name: 'Glycylcyclines',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(p)')],
    aliases: ['glycylcycline', 'glycylcyclines', 'tigecycline'],
    note: DOC_2025,
  },
  {
    key: 'eravacycline',
    name: 'Eravacycline',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(q)')],
    aliases: ['eravacycline'],
    note: DOC_2025,
  },
  {
    key: 'omadacycline',
    name: 'Omadacycline',
    category: 'banned',
    kind: 'antibiotic',
    sources: [eu('(1)(r)')],
    aliases: ['omadacycline'],
    note: DOC_2025,
  },

  // ── EU 2022/1255 Annex (2) antivirals, (3) antiprotozoals ──────────────────
  ...EU_ANTIVIRALS.map(
    ([key, name, ref, extra]): BannedSubstance => ({
      key,
      name,
      category: 'banned',
      kind: 'antiviral',
      sources: [eu(ref)],
      aliases: [key.replace(/_/g, ' '), ...extra],
      note: DOC_2025,
    }),
  ),
  {
    key: 'nitazoxanide',
    name: 'Nitazoxanide',
    category: 'banned',
    kind: 'antiprotozoal',
    sources: [eu('(2)(j)'), eu('(3)(a)')],
    aliases: ['nitazoxanide'],
    note: `Listed as both antiviral and antiprotozoal. ${DOC_2025}`,
  },

  // ── Leads with no verified primary source yet ──────────────────────────────
  {
    key: 'colistin',
    name: 'Colistin',
    category: 'banned',
    kind: 'antibiotic',
    sources: [],
    aliases: ['colistin', 'colistine', 'polymyxin e'],
    localAliases: {
      hi: ['कोलिस्टिन'],
      te: ['కొలిస్టిన్'],
      ta: ['கொலிஸ்டின்'],
      bn: ['কোলিস্টিন'],
      or: ['କୋଲିଷ୍ଟିନ'],
    },
    note: `${UNSOURCED} A July 2019 MoHFW s.26A prohibition for food-producing animals incl. aqua farming is widely reported, but its gazette text was not fetched.`,
  },
  {
    key: 'malachite_green',
    name: 'Malachite green',
    category: 'banned',
    kind: 'dye',
    sources: [],
    aliases: ['malachite green', 'malachite'],
    localAliases: {
      hi: ['मैलाकाइट ग्रीन'],
      te: ['మలాకైట్ గ్రీన్'],
      ta: ['மலாக்கைட் பச்சை'],
      bn: ['ম্যালাকাইট গ্রিন'],
      or: ['ମାଲାକାଇଟ ଗ୍ରୀନ'],
    },
    note: `${UNSOURCED} CAA Guidelines §11.6 only says its use "should be avoided"; the EU zero-tolerance claim is unverified.`,
  },
  {
    key: 'crystal_violet',
    name: 'Crystal violet (gentian violet)',
    category: 'banned',
    kind: 'dye',
    sources: [],
    aliases: ['crystal violet', 'gentian violet'],
    note: UNSOURCED,
  },
];
