// GENERATED by `npm run gen:banned` from backend/src/banned-substances/banned-substance-matcher.core.ts.
// Do not edit. source-sha256: ccbe82b554f801209ac5e59d59b3145289a9577d8d3a680f5c4621b5d7845502

import type { BannedSubstance } from './bannedSubstances.generated';

// Shared banned-substance matcher (spec D1). Copied VERBATIM into the app by
// `npm run gen:banned` in frontend/, so server and client can never disagree
// on what matches. Keep it dependency-free (type import only). Edit it here.
//
// Matching is whole-token and Unicode-aware:
//   1. normalise text and alias the same way: NFC, lowercase, Latin "ph"→"f"
//      (so "sulphamethoxazole" matches "sulfamethoxazole"), and every run of
//      characters that is not a letter, combining mark or digit becomes ONE
//      space (so "nalidixic-acid" matches "nalidixic acid");
//   2. an alias matches when " alias " occurs inside " text ".
// Combining marks (\p{M}) count as part of a word: Indic vowel signs and
// viramas are marks, and treating them as separators would split one word.
// Hermes (RN 0.81) compiles \p{L}/\p{M}/\p{N} with the u flag; checked with
// the app's own hermesc, see the D1 PR.

/** Structural subset the matcher needs; old persisted lists have no localAliases. */
type Matchable = Pick<BannedSubstance, 'aliases'> & {
  localAliases?: BannedSubstance['localAliases'];
};

export type BannedSubstanceFlag = 'none' | 'restricted' | 'banned';

export function normalizeForMatch(text: string): string {
  let s = text;
  try {
    s = s.normalize('NFC');
  } catch {
    // An engine without normalize() still matches already-composed text.
  }
  return s
    .toLowerCase()
    .replace(/ph/g, 'f') // "ph" only exists in Latin script, so this is Latin-only.
    .replace(/[^\p{L}\p{M}\p{N}]+/gu, ' ')
    .trim();
}

function allAliases(sub: Matchable): string[] {
  const local = sub.localAliases
    ? Object.values(sub.localAliases).flatMap((a) => a ?? [])
    : [];
  return [...(sub.aliases ?? []), ...local];
}

/** Every substance (once each) referenced in `text`, in list order. */
export function matchSubstances<T extends Matchable>(
  text: string | null | undefined,
  list: readonly T[],
): T[] {
  if (!text) return [];
  const hay = ` ${normalizeForMatch(text)} `;
  if (hay.trim() === '') return [];
  return list.filter((sub) =>
    allAliases(sub).some((alias) => {
      const a = normalizeForMatch(alias);
      return a !== '' && hay.includes(` ${a} `);
    }),
  );
}

/** Worst flag across the matches: banned > restricted > none. */
export function flagOf(found: ReadonlyArray<{ category: string }>): BannedSubstanceFlag {
  if (found.some((s) => s.category === 'banned')) return 'banned';
  return found.length > 0 ? 'restricted' : 'none';
}
