import type { ReportData } from '../../types';
import { renderReportHtml } from '../renderReportHtml';

const base = (): ReportData => ({
    meta: {
        documentTitle: 'Cycle report',
        farmName: 'Kadalur Farm',
        pondName: 'Pond 3',
        cycleLabel: 'Crop 2026-A',
        periodLabel: '1 Jun – 5 Sep 2026',
        generatedAt: '5 Sep 2026, 4:10 pm',
        attribution: 'Generated by Neerani',
    },
    stats: [
        { label: 'Survival', value: '82%', hint: 'over 92 days' },
        { label: 'FCR', value: '1.42' },
    ],
    tables: [
        {
            key: 'feed',
            title: 'Feed',
            columns: ['Date', 'Feed (kg)', 'Note'],
            rows: [
                ['1 Jun', '12.5', 'morning'],
                ['2 Jun', '13.0', 'evening'],
            ],
            numericColumns: [1],
            total: ['Total', '25.5', ''],
        },
    ],
    disclaimer: 'A record of what was entered. Not a guarantee.',
});

describe('renderReportHtml', () => {
    it('renders a complete document with headings, stats and rows', () => {
        const html = renderReportHtml(base());
        expect(html.startsWith('<!DOCTYPE html>')).toBe(true);
        expect(html).toContain('<html lang="en">');
        expect(html).toContain('Neerani');
        expect(html).toContain('Cycle report');
        expect(html).toContain('Kadalur Farm');
        expect(html).toContain('Pond 3');
        expect(html).toContain('1 Jun – 5 Sep 2026');
        expect(html).toContain('<div class="stat-label">Survival</div>');
        expect(html).toContain('<div class="stat-value">82%</div>');
        expect(html).toContain('over 92 days');
        expect(html).toContain('<h2>Feed</h2>');
        expect(html).toContain('morning');
        expect(html).toContain('Generated by Neerani');
        expect(html).toContain('A record of what was entered. Not a guarantee.');
        expect(html.trimEnd().endsWith('</html>')).toBe(true);
    });

    it('sets the document language when given one', () => {
        expect(renderReportHtml(base(), 'ta')).toContain('<html lang="ta">');
    });

    it('right-aligns only the numeric columns', () => {
        const html = renderReportHtml(base());
        expect(html).toContain('<td class="num">12.5</td>');
        expect(html).toContain('<td>morning</td>');
        expect(html).toContain('<th class="num">Feed (kg)</th>');
    });

    describe('escaping', () => {
        it('neutralises a farm named <script>', () => {
            const data = base();
            data.meta.farmName = '<script>alert(1)</script>';
            const html = renderReportHtml(data);
            expect(html).not.toContain('<script');
            expect(html).not.toContain('</script>');
            expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
        });

        it('escapes ampersands and quotes everywhere they can appear', () => {
            const data = base();
            data.meta.pondName = 'A & B "north"';
            data.meta.documentTitle = "Ravi's & Co <report>";
            data.stats[0].label = 'P&L';
            data.stats[0].value = '<b>x</b>';
            data.stats[0].hint = 'a & b';
            data.tables[0].title = 'Feed & Water';
            data.tables[0].columns[0] = 'Date & time';
            data.tables[0].rows[0][2] = '<img src=x onerror=alert(1)>';
            data.tables[0].total![0] = 'Total & tax';
            data.disclaimer = 'x & y';
            data.meta.attribution = 'Neerani & partners';
            const html = renderReportHtml(data);

            // Nothing farmer-typed escapes as markup.
            expect(html).not.toContain('<img');
            expect(html).toContain('&lt;img src=x onerror=alert(1)&gt;');
            expect(html).toContain('A &amp; B &quot;north&quot;');
            expect(html).toContain('Ravi&#39;s &amp; Co &lt;report&gt;');
            expect(html).toContain('P&amp;L');
            expect(html).toContain('&lt;b&gt;x&lt;/b&gt;');
            expect(html).toContain('Feed &amp; Water');
            expect(html).toContain('Date &amp; time');
            expect(html).toContain('Total &amp; tax');
            expect(html).toContain('Neerani &amp; partners');
            expect(html).toContain('x &amp; y');
            // A bare `&` never survives — every one is part of an entity.
            expect(html.replace(/&(amp|lt|gt|quot|middot|mdash|#39);/g, '')).not.toContain('&');
        });
    });

    it('renders an explicit empty state for a table with no rows', () => {
        const data = base();
        data.tables[0].rows = [];
        delete data.tables[0].total;
        const html = renderReportHtml(data);
        expect(html).toContain('<h2>Feed</h2>');
        expect(html).toContain('<td class="empty" colspan="3">&mdash;</td>');
        expect(html).toContain('<th>Date</th>'); // header row survives
    });

    it('renders a single row without a total', () => {
        const data = base();
        data.tables[0].rows = [['1 Jun', '12.5', 'only']];
        delete data.tables[0].total;
        const html = renderReportHtml(data);
        expect(html).toContain('only');
        expect(html).not.toContain('<tfoot>');
        expect(html).not.toContain('class="total"');
    });

    it('renders the total row distinctly when present', () => {
        const html = renderReportHtml(base());
        expect(html).toContain('<tfoot><tr class="total">');
        expect(html).toContain('<td class="num">25.5</td>');
        expect(html).toContain('tr.total td'); // and the CSS that distinguishes it
    });

    it('omits excluded sections entirely — no empty heading', () => {
        const data = base();
        data.tables = [];
        const html = renderReportHtml(data);
        expect(html).not.toContain('<h2>');
        expect(html).not.toContain('<table class="data">');
        // The rest of the document still renders.
        expect(html).toContain('Cycle report');
        expect(html).toContain('Generated by Neerani');
    });

    it('omits the stat row when there are no stats', () => {
        const data = base();
        data.stats = [];
        expect(renderReportHtml(data)).not.toContain('class="stats"');
    });

    it('omits optional meta lines that are absent', () => {
        const data = base();
        delete data.meta.farmName;
        delete data.meta.pondName;
        delete data.meta.cycleLabel;
        delete data.meta.periodLabel;
        const html = renderReportHtml(data);
        expect(html).not.toContain('class="subject"');
        expect(html).toContain('5 Sep 2026, 4:10 pm'); // generatedAt still shown
    });

    it('carries the print rules that make a multi-page report readable', () => {
        const html = renderReportHtml(base());
        expect(html).toContain('@page { size: A4;');
        expect(html).toMatch(/table\.data thead \{ display: table-header-group; \}/);
        expect(html).toContain('page-break-inside: avoid');
        expect(html).toContain('page-break-after: avoid');
        expect(html).toContain('position: fixed'); // footer repeats per page
    });

    it('is self-contained — no network fetches', () => {
        const html = renderReportHtml(base());
        expect(html).not.toMatch(/https?:\/\//);
        expect(html).not.toContain('<link');
        expect(html).not.toContain('@import');
        expect(html).not.toContain('<img');
    });

    it('wraps very long cell values instead of overflowing', () => {
        const data = base();
        const paragraph = 'Note: '.repeat(200);
        data.tables[0].rows = [['1 Jun', '12.5', paragraph]];
        const html = renderReportHtml(data);
        expect(html).toContain(paragraph);
        expect(html).toContain('overflow-wrap: anywhere');
        expect(html).toContain('table-layout: fixed');
    });
});
